[terminal.shell]
# program = "/usr/local/bin/tmux"
program = "/opt/homebrew/bin/tmux"
args = [
  "new-session",
  "-A",     # attach if session already exists
  "-D",     # detach other clients
  "-s", "main"
]

[window]
startup_mode = "Fullscreen"

[font]
size = 20

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Up"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Down"
mods = "Alt"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[colors.bright]
black = "#002b36"
blue = "#839496"
cyan = "#93a1a1"
green = "#586e75"
magenta = "#6c71c4"
red = "#cb4b16"
white = "#fdf6e3"
yellow = "#657b83"

[colors.cursor]
cursor = "#839496"
text = "#002b36"

[colors.normal]
black = "#073642"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
red = "#dc322f"
white = "#eee8d5"
yellow = "#b58900"

[colors.primary]
background = "#002b36"
foreground = "#839496"
